Sample of generation of error for Stub.
========================================

::

    >>> from ludibrio import Stub

Should raise an error when making non-configured calls::

    >>> with Stub() as greetings:
    ...     greetings.called() >> 'returned'
    >>> print greetings.called()
    returned
    >>> print greetings.executeAnythingAndReturnError()
    Traceback (most recent call last):
    ...
    AttributeError: Stub Object received unexpected call. executeAnythingAndReturnError


Should raise an error if programmed calls are executed with incorrect parameters::

    >>> with Stub() as greetings:
    ...     greetings.hi(name='Gustavo') >> 'Hi, Gustavo'
    >>> print greetings.hi('fulano')
    Traceback (most recent call last):
    ...
    AttributeError: Stub Object received unexpected call. hi('fulano')

